[build]
  publish = "build"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/oauth-redirect"
  to = "/oauth-redirect.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
