name: Supabase Admin Backup

on:
  schedule:
    - cron: '0 0 * * 0' # Weekly on Sunday at midnight
  workflow_dispatch: # Allow manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run admin backup script
        run: node scripts/backup-supabase-admin.js
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          
      - name: Create backup branch if it doesn't exist
        run: |
          git fetch origin
          git checkout backup || git checkout -b backup
          git pull origin backup --rebase || true
          
      - name: Force add backups
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          mkdir -p .backups
          echo "{\"timestamp\": \"$(date -u +"%Y-%m-%dT%H:%M:%SZ")\", \"status\": \"completed\"}" > .backups/backup_info.json
          git add -f .backups/
          git commit -m "Automated backup $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push -f origin backup