name: Daily Push Notifications

on:
  schedule:
    - cron: '0 13 * * *'  # 8:00 AM Central Time (13:00 UTC)
    - cron: '0 17 * * *'  # 12:00 PM Central Time (17:00 UTC) 
    - cron: '0 21 * * *'  # 4:00 PM Central Time (21:00 UTC)
    - cron: '0 23 * * *'  # 6:00 PM Central Time (23:00 UTC)
    - cron: '0 2 * * *'   # 9:00 PM Central Time (02:00 UTC next day)
  workflow_dispatch:  # Allow manual trigger

jobs:
  trigger-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send daily push notifications
        run: |
          # Send push notifications via Netlify function
          # Note: NOTIFICATION_API_KEY is configured in GitHub repository secrets
          API_KEY=$(echo -n "${{ secrets.NOTIFICATION_API_KEY }}" | perl -MURI::Escape -ne 'print uri_escape($_)')
          RESPONSE=$(curl -X POST "https://fintask.netlify.app/.netlify/functions/send-push-reminders?key=${API_KEY}" -s)
          echo "Function response: $RESPONSE"
          if [[ "$RESPONSE" == *"sent"* || "$RESPONSE" == *"No subscriptions"* ]]; then
            echo "✅ Push notifications sent successfully"
          else
            echo "❌ Push notification may have failed: $RESPONSE"
          fi