name: Daily Task Notifications

on:
  schedule:
    - cron: '0 13 * * *'  # 8:00 AM Central Time (13:00 UTC)
  workflow_dispatch:  # Allow manual trigger

jobs:
  trigger-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger notification function
        run: |
          curl -X POST "https://us-central1-${{ secrets.FIREBASE_PROJECT_ID }}.cloudfunctions.net/sendDailyTaskReminders" \
          -H "Authorization: Bearer ${{ secrets.NOTIFICATION_API_KEY }}" \
          -H "Content-Type: application/json" \
          --fail
      
      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Daily notification trigger failed`,
              body: `The daily notification trigger failed. Please check the [workflow run](${process.env.GITHUB_SERVER_URL}/${context.repo.owner}/${context.repo.repo}/actions/runs/${process.env.GITHUB_RUN_ID}) for details.`
            })