# DISABLED: Replaced with Netlify Scheduled Functions
# This workflow is kept for manual testing only

name: Daily Push Notifications (DISABLED)

on:
  workflow_dispatch:  # Manual trigger only - scheduled jobs moved to Netlify

jobs:
  trigger-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send daily push notifications
        run: |
          # Send push notifications via Netlify function
          # Note: NOTIFICATION_API_KEY is configured in GitHub repository secrets
          API_KEY=$(echo -n "${{ secrets.NOTIFICATION_API_KEY }}" | perl -MURI::Escape -ne 'print uri_escape($_)')
          RESPONSE=$(curl -X POST "https://fintask.netlify.app/.netlify/functions/send-push-reminders?key=${API_KEY}" -s)
          echo "Function response: $RESPONSE"
          if [[ "$RESPONSE" == *"sent"* || "$RESPONSE" == *"No subscriptions"* ]]; then
            echo "✅ Push notifications sent successfully"
          else
            echo "❌ Push notification may have failed: $RESPONSE"
          fi