name: Daily Notifications (9:00 AM CT)

on:
  schedule:
    - cron: '0 14 * * *'  # 9:00 AM Central Time (14:00 UTC)
  workflow_dispatch:  # Allow manual trigger

jobs:
  send-notifications:
    runs-on: ubuntu-latest
    steps:
      - name: Send daily email reminders
        run: |
          # Send email notifications via Netlify function
          API_KEY=$(echo -n "${{ secrets.NOTIFICATION_API_KEY }}" | perl -MURI::Escape -ne 'print uri_escape($_)')
          EMAIL_RESPONSE=$(curl -X POST "https://fintask.netlify.app/.netlify/functions/send-daily-reminders?key=${API_KEY}" -s)
          echo "Email function response: $EMAIL_RESPONSE"
          if [[ "$EMAIL_RESPONSE" == *"sent"* || "$EMAIL_RESPONSE" == *"No tasks"* ]]; then
            echo "✅ Email notifications sent successfully"
          else
            echo "❌ Email notification may have failed: $EMAIL_RESPONSE"
          fi

      - name: Send daily push notifications
        run: |
          # Send push notifications via Netlify function
          API_KEY=$(echo -n "${{ secrets.NOTIFICATION_API_KEY }}" | perl -MURI::Escape -ne 'print uri_escape($_)')
          PUSH_RESPONSE=$(curl -X POST "https://fintask.netlify.app/.netlify/functions/send-push-reminders?key=${API_KEY}" -s)
          echo "Push function response: $PUSH_RESPONSE"
          if [[ "$PUSH_RESPONSE" == *"sent"* || "$PUSH_RESPONSE" == *"No subscriptions"* ]]; then
            echo "✅ Push notifications sent successfully"
          else
            echo "❌ Push notification may have failed: $PUSH_RESPONSE"
          fi

      - name: Summary
        run: |
          echo "📱 Daily notification summary:"
          echo "   📧 Email reminders: Processed"
          echo "   🔔 Push notifications: Processed"
          echo "   ⏰ Scheduled for 9:00 AM Central Time daily"