name: Daily Email Reminders (9:00 AM CT)

on:
  schedule:
    - cron: '0 14 * * *'  # 9:00 AM Central Time (14:00 UTC)
  workflow_dispatch:  # Allow manual trigger

jobs:
  trigger-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send daily email reminders
        run: |
          # Send email notifications via Netlify function
          API_KEY=$(echo -n "${{ secrets.NOTIFICATION_API_KEY }}" | perl -MURI::Escape -ne 'print uri_escape($_)')
          RESPONSE=$(curl -X POST "https://fintask.netlify.app/.netlify/functions/send-daily-reminders?key=${API_KEY}" -s)
          echo "Function response: $RESPONSE"
          if [[ "$RESPONSE" == *"sent"* || "$RESPONSE" == *"No tasks"* ]]; then
            echo "✅ Email notifications sent successfully"
          else
            echo "❌ Email notification may have failed: $RESPONSE"
          fi