name: E2E Tests

on:
  push:
    branches: [ main, 'feature/*', 'hotfix/*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  e2e_tests:
    name: E2E Test
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    # Build and start the app
    - name: Build and start app
      run: |
        # Create .env file for build
        echo "REACT_APP_SUPABASE_URL=$REACT_APP_SUPABASE_URL" > .env
        echo "REACT_APP_SUPABASE_ANON_KEY=$REACT_APP_SUPABASE_ANON_KEY" >> .env
        echo "REACT_APP_SITE_URL=http://localhost:3000" >> .env
        echo "REACT_APP_FIREBASE_API_KEY=${REACT_APP_FIREBASE_API_KEY:-dummy-key}" >> .env
        
        # Build and start the app
        npm run build
        npx serve -s build -l 3000 &
        
        # Wait for server to start
        timeout=30
        while ! curl -s http://localhost:3000 > /dev/null; do
          if [ $timeout -le 0 ]; then
            echo "Server failed to start"
            exit 1
          fi
          echo "Waiting for server... ($timeout seconds left)"
          sleep 1
          timeout=$((timeout - 1))
        done
        echo "Server ready at http://localhost:3000"
      env:
        REACT_APP_SUPABASE_URL: ${{ secrets.REACT_APP_SUPABASE_URL }}
        REACT_APP_SUPABASE_ANON_KEY: ${{ secrets.REACT_APP_SUPABASE_ANON_KEY }}
        REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY || 'dummy-key' }}
    
    # Configure Git to eliminate warnings
    - name: Configure Git
      run: |
        git config --global init.defaultBranch main
        git config --global advice.detachedHead false
    
    # Update browser data
    - name: Update browser data
      run: npx update-browserslist-db@latest
    
    # Run Cypress tests
    - name: Run E2E Tests
      run: npm run test:e2e:essential
      env:
        TERM: xterm-256color
        CYPRESS_baseUrl: http://localhost:3000
        CYPRESS_TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
        CYPRESS_TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
    
    # Upload Cypress artifacts only if they exist
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: cypress-screenshots
        path: cypress/screenshots/
        retention-days: 30
        if-no-files-found: ignore
    
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: cypress-videos
        path: cypress/videos/
        retention-days: 30
        if-no-files-found: ignore