name: Test Local Server

on:
  workflow_dispatch:

jobs:
  test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Create static test page
        run: |
          mkdir -p public_test
          cat > public_test/index.html << 'EOL'
          <!DOCTYPE html>
          <html>
          <head>
            <title>Test Page</title>
          </head>
          <body>
            <h1>Test Page</h1>
            <form>
              <input type="email" placeholder="Email">
              <input type="password" placeholder="Password">
              <button type="submit">Login</button>
            </form>
          </body>
          </html>
          EOL
      
      - name: Start server
        run: |
          npx serve public_test -l 3000 &
          echo $! > server.pid
          sleep 5
      
      - name: Check server content
        run: |
          echo "Server response:"
          curl -s http://localhost:3000
          
          echo -e "\n\nChecking for form tag:"
          curl -s http://localhost:3000 | grep -q 'form' && echo "Form found" || echo "Form NOT found"
          
          echo -e "\n\nChecking raw HTML:"
          curl -s http://localhost:3000 | cat -A